## Broadcasting

NumPy has a powerful feature called **broadcasting** in which the smaller of two NumPy arrays is repeated to make it match a larger NumPy array, if possible. Here, I show examples of ndarrays that have the the same number of dimensions (i.e. they are both 2D) and examples in which one is 2D and the other is 1D. The distinction is important because there are slightly different rules.

In [1]:
import numpy as np

### Example 1: Increasing dimensions on left

When one array has fewer dimensions that the other, broadcasting works only when the smaller array can be repeated along a dimension *to the left*. This is best explained by example:

A is a 2D array with shape (3,5)
$$A = \begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
\end{pmatrix}$$

and b is a 1D array with shape (5,)

$$b = 
\begin{pmatrix} 
2 & 4 & 6 & 8 & 10\\
\end{pmatrix}$$

`A+b` can be computed with broadcasting because NumPy can add an extra dimension to the left (i.e. it can make the shape (1,5)). It behaves as if b is repeated three times (i.e. its shape is (3,5) with the rows repeated).

It effectively does this math

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
\end{pmatrix} + 
\begin{pmatrix}
2 & 4 & 6 & 8 & 10\\
2 & 4 & 6 & 8 & 10\\
2 & 4 & 6 & 8 & 10\\
\end{pmatrix}$$

though it doesn't actually waste space like this

In [9]:
A = np.array( [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b = np.array( [2,4,6,8,10])
print("A\n",A)
print(f'A has shape ({A.shape[0]},{A.shape[1]})')
print("b\n",b)
print(f'b has shape ({b.shape[0]},)')

A
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
A has shape (3,5)
b
 [ 2  4  6  8 10]
b has shape (5,)


In [10]:
C = A + b
print("C\n",C)
print(f'C has shape ({C.shape[0]},{C.shape[1]})')

C
 [[ 3  6  9 12 15]
 [ 8 11 14 17 20]
 [13 16 19 22 25]]
C has shape (3,5)


### Example 2: repeating along dimension of size 1 (row)

Broadcasting works with two arrays of the same dimensionality as long as the shapes line up. That means, for each axis, the number of elements along that axis are either the same for both arrays or one of the arrays has just 1 element along that axis. Again, examples make it clearer.

A is a 2D array with shape (3,5)
$$A = \begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
\end{pmatrix}$$

b is a 2D array with shape (1,5)

$$b = 
\begin{pmatrix} 
2 & 4 & 6 & 8 & 10\\
\end{pmatrix}$$

`A+b` can be computed with broadcasting because NumPy sees that number of elements along axis 1 is identical for `A` and `b` and that `b` has just 1 element along axis 0. It behaves as if b is repeated three times (three rows). (i.e. This example works out just like the previous example.)

It effectively does this math

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
\end{pmatrix} + 
\begin{pmatrix}
2 & 4 & 6 & 8 & 10\\
2 & 4 & 6 & 8 & 10\\
2 & 4 & 6 & 8 & 10\\
\end{pmatrix}$$

though it doesn't actually waste space like this

In [26]:
A = np.array( [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b = np.array( [[2,4,6,8,10]])
print("A\n",A)
print(f'A has shape ({A.shape[0]},{A.shape[1]})')
print("b\n",b)
print(f'b has shape ({b.shape[0]},{b.shape[1]})')

A
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
A has shape (3,5)
b
 [[ 2  4  6  8 10]]
b has shape (1,5)


In [27]:
C = A + b
print("C\n",C)
print(f'C has shape ({C.shape[0]},{C.shape[1]})')

C
 [[ 3  6  9 12 15]
 [ 8 11 14 17 20]
 [13 16 19 22 25]]
C has shape (3,5)


### Example 3: repeating along dimension of size 1 

Here is another example with two 2D arrays. This time, both have 3 elements along axis 0 and one has only one element along axis 1.

A is a 2D array with shape (3,5)
$$A = \begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
\end{pmatrix}$$

b is a 2D array with shape (3,1)

$$b = 
\begin{pmatrix} 
3\\
5\\
7\\
\end{pmatrix}$$

`A+b` can be computed with broadcasting because NumPy sees that number of elements along axis 0 is identical for `A` and `b` and that `b` has just 1 element along axis 1. It behaves as if b is repeated five times (five columns).


It effectively does this math

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
\end{pmatrix} + 
\begin{pmatrix}
3 & 3 & 3 & 3 & 3\\
5 & 5 & 5 & 5 & 5\\
7 & 7 & 7 & 7 & 7\\
\end{pmatrix}$$

though it doesn't actually waste space like this

In [28]:
A = np.array( [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b = np.array( [[3],[5],[7]])
print("A\n",A)
print(f'A has shape ({A.shape[0]},{A.shape[1]})')
print("b\n",b)
print(f'b has shape ({b.shape[0]},{b.shape[1]})')

A
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
A has shape (3,5)
b
 [[3]
 [5]
 [7]]
b has shape (3,1)


In [29]:
C = A + b
print("C\n",C)
print(f'C has shape ({C.shape[0]},{C.shape[1]})')

C
 [[ 4  5  6  7  8]
 [11 12 13 14 15]
 [18 19 20 21 22]]
C has shape (3,5)


### Example 4: doesn't work because we can't expand on left

This is an example that seems like it should work, but it doesn't beacuse it breaks the rule that the array with fewer dimensions needs to have an axis added to the left.

A is a 2D array with shape (3,5)
$$A = \begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
\end{pmatrix}$$

and b is a 1D array with shape (3,)

$$b = 
\begin{pmatrix} 
3 & 5 & 7\\
\end{pmatrix}$$

`A+b` **cannot** be computed with broadcasting because NumPy cannot add an extra dimension to the left (i.e. (1,3) wouldn't line up with (3,5)).


It effectively does this math

$$\begin{pmatrix}
1 & 2 & 3 & 4 & 5\\
6 & 7 & 8 & 9 & 10\\
11 & 12 & 13 & 14 & 15\\
\end{pmatrix} + 
\begin{pmatrix}
2 & 4 & 6 & 8 & 10\\
2 & 4 & 6 & 8 & 10\\
2 & 4 & 6 & 8 & 10\\
\end{pmatrix}$$

though it doesn't actually waste space like this

In [30]:
A = np.array( [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
b = np.array( [3,5,7])
print("A\n",A)
print(f'A has shape ({A.shape[0]},{A.shape[1]})')
print("b\n",b)
print(f'b has shape ({b.shape[0]},)')

A
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
A has shape (3,5)
b
 [3 5 7]
b has shape (3,)


In [25]:
C = A + b

ValueError: operands could not be broadcast together with shapes (3,5) (3,) 

How do we fix it? 

We explicitly add the dimension to the right, so that A still has shape (3,5) but now b has shape (3,1). This then becomes identical to Example 3.

In [31]:
A = np.array( [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
## Make b a 2D array instead of a 1D array
b = np.array( [3,5,7]).reshape( (3,1)) # Fix with the reshape!!
print("A\n",A)
print(f'A has shape ({A.shape[0]},{A.shape[1]})')
print("b\n",b)
print(f'b has shape ({b.shape[0]},{b.shape[1]})')
C = A + b
print("C\n",C)
print(f'C has shape ({C.shape[0]},{C.shape[1]})')

A
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
A has shape (3,5)
b
 [[3]
 [5]
 [7]]
b has shape (3,1)
C
 [[ 4  5  6  7  8]
 [11 12 13 14 15]
 [18 19 20 21 22]]
C has shape (3,5)
